server:
  port: 9712
  servlet:
    context-path: /auth

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Bangkok
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    staticPathPattern: /content/**
  resources:
    staticLocations: classpath:/files/
  cache:
    type: redis
    redis:
      time-to-live: 120000 #2 minutes
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    registry-fetch-interval-seconds: 5
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER}

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
file:
  supportTypes: png, jpg, jpeg, svg

cleaner:
  delay-time: ${CLEANER_DELAY_TIME}
  captcha:
    exp: ${CLEANER_CAPTCHA_EXP}
  otp:
    exp: ${CLEANER_OTP_EXP}

odp:
  api-key: ${ODP_API_KEY}
  url-user-info: ${ODP_USERINFO_URL}
  server-url: ${ODP_SERVER_URL}

email:
  server-url: ${EMAIL_SERVER_URL}
  backup-url: ${EMAIL_BACKUP_URL}
  apikey: ${EMAIL_APIKEY}

#------------Local-------------------
DEFAULT_TOKEN: Bearer shdaiuahi34$@#42iowjio4234@#$@#$@#$I@h2io34h23$@#$H@#IP$2h4khdaduklfhearuERERBJE$#$N#$IDSAFasfasfnja
DEFAULT_SSOID: "ee090625-e293-4ccc-8250-f8a86925305e"
DATABASE_URL: jdbc:mysql://10.60.158.90:8000/its?useSSL=false
DATABASE_USER: its
DATABASE_PASS: Its@2021
EUREKA_SERVER: http://localhost:9710/eureka/

CLEANER_DELAY_TIME: 3600000 # 1 hour
CLEANER_CAPTCHA_EXP: 1800 # 0.5 hours
CLEANER_OTP_EXP: 300 # 3 minutes


ODP_API_KEY: eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IlVubGltaXRlZCIsIm5hbWUiOiJJVFNfQVBQIiwiaWQiOjUsInV1aWQiOiIwODIwNDRlYi0zNWM3LTQwOTgtODdkMS03NGY3YWUyNDVkOTcifSwiaXNzIjoiaHR0cHM6XC9cLzEwLjYwLjE1Ni4xMTA6OTQ0M1wvb2F1dGgyXC90b2tlbiIsInRpZXJJbmZvIjp7IlVubGltaXRlZCI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJQUk9EVUNUSU9OIiwicGVybWl0dGVkUmVmZXJlciI6IiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IlVzZXJNYW5hZ2VtZW50IiwiY29udGV4dCI6IlwvdXNlck1hbmFnZW1lbnRcLzEuMCIsInB1Ymxpc2hlciI6ImFkbWluIiwidmVyc2lvbiI6IjEuMCIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifV0sInBlcm1pdHRlZElQIjoiIiwiaWF0IjoxNjA5ODEyMjA5LCJqdGkiOiJmM2FlNGNmZi0yYWFhLTRhNzMtYjMxNy04NGRkMjI4NDc3ZjEifQ==.mJFPo7WBbT6yeJfuE6NRe0MdCfUM5MpJogryMHz2bevsHDb1bifBQCQRgaSI-rNLUg5sHxv9gafSkHVxAcuWmpwHo-LSYILUPxMbTHJrUccnEqvtLaRxbByIJH_GySEX2YE2_jEDNP9h7ZkG09jPYQaOacO1J5hACKmZ00AJD-nfcmcQmcbip_S4HtEW84soSClXWagzvHjAtMdm2JQQXlomm7GSve4WLSw4qtySsoDjod3Zsdu01JJGN8SfByS2dSrzmUbDgLtqVCkw-x6Qobked7XUfzQXX0s2bvjsfkby-ZWsOu7c2hzgaRru4W-msApTiXQ-lekVaHVPlUW9pQ==
#ODP_USERINFO_URL: http://10.60.156.110:8280/userManagement/1.0/auth/userInfo
#ODP_SERVER_URL: http://10.60.156.110:8280/userManagement/1.0

ODP_USERINFO_URL: http://10.60.158.87:9712/kc/auth/userInfo
ODP_SERVER_URL: http://10.60.158.87:9712/kc

EMAIL_SERVER_URL: http://10.240.192.62:9002
EMAIL_BACKUP_URL: http://localhost:9712/auth/captcha
EMAIL_APIKEY: hduisadgi3#$@hi32o4$@#$@#$jirj23iouoji32o432$@#$@#H$23i44234
FROM_EMAIL: support_idm@viettel.com.vn

REDIS_URL: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: "123"

IS_DEV_MODE: "true"
SHOW_SQL: "true"
SERVER_MODE: local

LOCK_DURATION: 120000 # minutes
LOCK_TIMES: 5 #times