server:
  port: 9734
  servlet:
    context-path: /device-management

spring:
  application:
    name: its-device-service-v1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Bangkok

feign:
  hystrix:
    enabled: true
  okhttp:    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    registry-fetch-interval-seconds: 5
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER}
scp:
  server-url: ${SCP_SERVER}

proxy:
  isProxy : true
  host : 10.61.11.42
  port : 3128

vms:
  server-url: http://10.60.156.75:9026
# ------------------- Local -------------------
DATABASE_URL: jdbc:mysql://10.60.158.90:8000/its_v1?useSSL=false
DATABASE_USER: its
DATABASE_PASS: Its@2021
EUREKA_SERVER: http://localhost:9710/eureka/
IS_DEV_MODE: true
#SCP_SERVER: http://10.60.158.89:8999
SCP_SERVER: http://10.30.176.77:5000
SCP_APIKEY: ajdhjkFAe34AR3caosjojeCAFAi53546DAopvkV
IOC_SERVER: http://10.60.158.39:9380/api
HOST_PROXY: "10.61.11.42"
PORT_PROXY: 3128





