apiVersion: apps/v1
kind: Deployment
metadata:
  name: its-highway-service-deployment
  labels:
    app: its
    module: its-highway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: its
      module: its-highway-service
  template:
    metadata:
      labels:
        app: its
        module: its-highway-service
    spec:
      containers:
        - name: its-highway-service-container
          image: 10.60.156.72/its/its-highway-service:__SERVICE_VERSION__
          ports:
            - containerPort: 9713
              protocol: TCP
          env:
            - name: EUREKA_SERVER
              value: "http://10.60.156.4:9710/eureka/"
            - name: DATABASE_URL
              value: "jdbc:mysql://10.60.158.45:8000/its"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASS
              value: "Its@2021"
      imagePullSecrets:
        - name: harbor2