apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: its-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: its/nfs
parameters:
  archiveOnDelete: "false"
