apiVersion: v1
kind: Service
metadata:
  name: its-device-service
  labels:
    app: its
    module: device-service
spec:
  ports:
  - name: its-device-service-port
    protocol: TCP
    port: 9714
    nodePort: 9714
  selector:
    app: its
    module: device-service
  type: NodePort